### ISSUE TITLE
Fatal error: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by johnbburg** [linusnorton/grunt-parallel-behat#23]
I receive this error running behat tests in a Jenkins job: 

```
Fatal error: Cannot read property '0' of undefined
TypeError: Cannot read property '0' of undefined
    at /var/lib/jenkins/workspace/my-project/behat/node_modules/grunt-parallel-behat/tasks/lib/BehatTask.js:101:58
    at Parser.<anonymous> (/var/lib/jenkins/workspace/my-project/behat/node_modules/xml2js/lib/xml2js.js:483:18)
    at Parser.emit (events.js:95:17)
    at Object.onclosetag (/var/lib/jenkins/workspace/my-project/behat/node_modules/xml2js/lib/xml2js.js:444:26)
    at emit (/var/lib/jenkins/workspace/my-project/behat/node_modules/sax/lib/sax.js:624:35)
    at emitNode (/var/lib/jenkins/workspace/my-project/behat/node_modules/sax/lib/sax.js:629:5)
    at closeTag (/var/lib/jenkins/workspace/my-project/behat/node_modules/sax/lib/sax.js:889:7)
    at Object.write (/var/lib/jenkins/workspace/my-project/behat/node_modules/sax/lib/sax.js:1436:13)
    at Parser.exports.Parser.Parser.parseString (/var/lib/jenkins/workspace/my-project/behat/node_modules/xml2js/lib/xml2js.js:502:31)
    at Parser.parseString (/var/lib/jenkins/workspace/my-project/behat/node_modules/xml2js/lib/xml2js.js:7:59)
```
[sic] on the new line after the error. The referenced line is https://github.com/linusnorton/grunt-parallel-behat/blob/0.4.6/tasks/lib/BehatTask.js#L101. Specifically, the first check in that if statement: ```result.testsuites.testsuite["0"]```

Note about the test I am running, it takes a long time, ~15-20 minutes or so. Could it be running into timeouts?

**Comment by johnbburg** [comment]
I think what's happening is that there is a permissions issue on where the jUnit results are being created. Here's what I get when I try to run the command directly. 

```
$ ./tests/behat/bin/behat -c ./tests/behat/behat.jenkins.yml ./tests/behat/features/MyProject/myFeature.feature -p dev -f junit --out tests/behat/test_results/dev/
PHP Warning:  fopen(/var/lib/jenkins/workspace/my-project/behat/tests/behat/test_results/dev/myfeature.xml): failed to open stream: Permission denied in /var/lib/jenkins/workspace/my-project/behat/tests/behat/vendor/behat/behat/src/Behat/Testwork/Output/Printer/Factory/FilesystemOutputFactory.php on line 63

                                                                  
  [Symfony\Component\Console\Exception\InvalidArgumentException]  
  The StreamOutput class needs a stream as its first argument.    
                                                                  

behat [-s|--suite SUITE] [-f|--format FORMAT] [-o|--out OUT] [--format-settings FORMAT-SETTINGS] [--init] [--lang LANG] [--name NAME] [--tags TAGS] [--role ROLE] [--story-syntax] [-d|--definitions DEFINITIONS] [--snippets-for [SNIPPETS-FOR]] [--snippets-type SNIPPETS-TYPE] [--append-snippets] [--no-snippets] [--strict] [--order ORDER] [--rerun] [--stop-on-failure] [--dry-run] [--] [<paths>]
```

So nothing to see here I guess, though it may be handy to have some more informative error handling from the string parser result function.

**Comment by linusnorton** [comment]
Thanks for following that up, I don't use this project very often any more so it takes me a while to spin things up and see what's going on

**Comment by johnbburg** [comment]
Thanks for responding! Re-examining this, I do have other test suites running successfully, so I'm doubting that it's a permissions issue and more on the timeout period. I'm new to debugging grunt tasks, and nodejs, so any pointers are appreciated. All my other tests are passing. Quick question, Where should the testsuite property be set?

**Comment by johnbburg** [comment]
Nevermind, it's parsing the XML test result.

**Comment by johnbburg** [comment]
Final follow up. It seems that it was a timeout issue. default is 5 minutes. So I added 

```
                options : {
                    timeout : 3600000,
                    ...
```

In my grunt behat config. For context, my tests just took 20 minutes to run. 

Edit: 3600000 = 1 hour in milliseconds.
